name: GitHub Apps Access
on: workflow_dispatch

defaults:
  run:
    

jobs:
  github_apps_access:
    name: github_apps_access
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch branch
        run: git fetch --depth 1 origin ${{ env.TARGET_BRANCH }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true
          working-directory: ruby/github_apps_test
      - name: run install_app_access
        run: |
          cd ruby/github_apps_test
          bundle exec ruby install_app_access.rb
