name: Nodejs Directory Push
on:
  push:
    paths:
      - "nodejs/*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "nodejs directory push"
    name: Greeting
    runs-on: ubuntu-latest
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: |
          cd ./nodejs
          cat index.ts
